---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      privileged: true
      pid_one_command: /lib/systemd/systemd
      volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
    run_list:
      - recipe[apt]
    attributes:
      apt:
        compile_time_update: true
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  - name: centos-6
    driver:
      image: dokken/centos-6

suites:
  - name: mysql_service
    run_list:
      - recipe[pacifica-dependencies::mysql_service]
    verifier:
      inspec_tests:
        - test/smoke/mysql_service
  - name: pgsql_service
    run_list:
      - recipe[pacifica-dependencies::pgsql_service]
    verifier:
      inspec_tests:
        - test/smoke/pgsql_service
  - name: ingestdb_setup
    run_list:
      - recipe[pacifica-dependencies::mysql_service]
      - recipe[pacifica-dependencies::ingestdb_setup]
    verifier:
      inspec_tests:
        - test/smoke/ingestdb_setup
  - name: cartdb_setup
    run_list:
      - recipe[pacifica-dependencies::mysql_service]
      - recipe[pacifica-dependencies::cartdb_setup]
    verifier:
      inspec_tests:
        - test/smoke/cartdb_setup
  - name: uniqueiddb_setup
    run_list:
      - recipe[pacifica-dependencies::mysql_service]
      - recipe[pacifica-dependencies::uniqueiddb_setup]
    verifier:
      inspec_tests:
        - test/smoke/uniqueiddb_setup
  - name: metadatadb_setup
    run_list:
      - recipe[pacifica-dependencies::pgsql_service]
      - recipe[pacifica-dependencies::metadatadb_setup]
    verifier:
      inspec_tests:
        - test/smoke/metadatadb_setup
  - name: rabbitmq
    run_list:
      - recipe[pacifica-dependencies::rabbitmq]
    verifier:
      inspec_tests:
        - test/smoke/rabbitmq
  - name: elasticsearch
    run_list:
      - recipe[pacifica-dependencies::elasticsearch]
    verifier:
      inspec_tests:
        - test/smoke/elasticsearch
