dist: trusty
sudo: required
group: edge
services: docker
stages:
- lint
- test
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

install: echo "skip bundle install"

before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

env:
  matrix:
  - T=mysql-service
  - T=pgsql-service
  - T=ingestdb-setup
  - T=cartdb-setup
  - T=uniqueiddb-setup
  - T=metadatadb-setup
  - T=rabbitmq
  - T=elasticsearch

script:
- /opt/chefdk/embedded/bin/chef --version
- /opt/chefdk/embedded/bin/chef gem install kitchen-dokken
- /opt/chefdk/embedded/bin/cookstyle --version
- /opt/chefdk/embedded/bin/foodcritic --version
- /opt/chefdk/embedded/bin/rspec --version
- /opt/chefdk/embedded/bin/kitchen test $T -d always


jobs:
  include:
  - stage: lint
    python: 3.6
    language: python
    services:
    sudo:
    script:
    - pip install pre-commit
    - pre-commit run -a

notifications:
  email:
    recipients:
    - dmlb2000@gmail.com
    - gitbytes@gmail.com
    on_failure: never
    on_success: always
